maurodatamapper:
    openidConnect:
        google:
            enabled: true
        microsoft:
            enabled: true
        keycloak:
            enabled: true
            baseUrl: http://localhost