maurodatamapper:
    openidConnect:
        google:
            enabled: true
        microsoft:
            enabled: true
            tenant: common
        keycloak:
            enabled: true
            issuerUrl: http://localhost