maurodatamapper:
    openidConnect:
        session:
            timeout: 10m
        google:
            enabled: false
        microsoft:
            enabled: false
            tenant: common
        keycloak:
            enabled: true